### ISSUE TITLE
onDrawerStateChanged

### ISSUE THREAD

**Issue by LinkOut** [balysv/material-menu#20]
I v implemented material-menu successfully on my project..

I have one question:

instead of using : setState(MaterialMenuDrawable.IconState.ARROW) 
i v tried : animatePressedState(MaterialMenuDrawable.IconState.ARROW);

Coz id like to have that circle animation, but it does not works..

Suggestions?

**Comment by balysv** [comment]
I will be removing the click state completely and leave up to the developers to implement it the way they want it #38
