### ISSUE TITLE
Maven Error(25,0)

### ISSUE THREAD

**Issue by TurKurT656** [balysv/material-menu#24]
when i try to import this to my project in android studio 1.0 rc2 i have this error:

Error:(25, 0) Could not read script 'C:\ADTBundle\StudioWorkspace\MyApplication\maven_push.gradle' as it does not exist.

i dont know how to import this toolbar lib to my project can you help me with a step by step guide?

**Comment by gaoneng102** [comment]
thank you ,it worked for me ~~
