### ISSUE TITLE
Problem when importing via Android-Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [balysv/material-menu#28]
I get this error message:

![untitled20150107125419](https://cloud.githubusercontent.com/assets/5357526/5644457/56b1e6aa-966c-11e4-884e-bc90bba2a1e3.png)

What should I do? I already have the latest version of Android-Studio, and I already have a lot of build-tools versions installed.

**Comment by balysv** [comment]
Please do not create issues irrelevant to this project.
There are plenty of resources online that can help you with general setup, i.e StackOverflow

**Comment by AndroidDeveloperLB** [comment]
But I have found them, and yet it didn't work:
http://stackoverflow.com/questions/24599785/android-studio-unsupported-version-of-gradle-plugin

I wanted to import the demo in order to show you the problem I've reported here:
https://github.com/balysv/material-menu/issues/27

Android-Studio has Gradle version "2.2.1" and yet it still doesn't work. I've tried to put the Gradle library folder content into the "plugins/gradle/lib/" folder , and it didn't help.

**Comment by AndroidDeveloperLB** [comment]
Now I've somehow managed to import it, but it says:

"Error:Library projects cannot set applicationId. applicationId is set to 'com.balysv.materialmenu' in default config.
Gradle 'material-menu' project refresh failed"

**Comment by balysv** [comment]
The demo uses some older version of the build tools. Update them in `build.gradle` dependencies after importing and you should be able to run it. That's what the error message said anyway.

**Comment by AndroidDeveloperLB** [comment]
Can you please put a tutorial on the main webpage, to show how to import it on the latest version of Android-Studio? When I use Git-imporing, it shows this error and I can't edit anything. When I clone the project and then choose to import, it asks for "gradle home" . 
Only on Eclipse I've succeed importing, but just the library and not the samples.

**Comment by balysv** [comment]
I don't think that's necessary. I've updated build tools versions, it should be imported easily now.

**Comment by AndroidDeveloperLB** [comment]
Oh thank you !
It got imported without a problem now.
However, I still see the issue I've reported before (but not on the demo), so I have no idea what's going on. I will need to investigate it further. I've even tried to make a sample but it worked fine too.
