### ISSUE TITLE
Request: allow to show the clicking effect via code

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [balysv/material-menu#29]
If it's in "burger" mode, I'd like to make a clicking effect in case the user clicks on it.

I've tried this:

materialMenuView.animatePressedState(IconState.BURGER);

but it doesn't do anything. Also tried to call "setState" before calling the above. 

Is there a way to allow clicking effect ?

**Comment by balysv** [comment]
Most information of how to get the circle clicked state is here https://github.com/balysv/material-menu#circle-pressed-state

What API level are you having problems with?

**Comment by AndroidDeveloperLB** [comment]
both 4.2 and 5.0 don't show the clicked effect. Can you please help?
When switching between different states, it works, but when it's on the same state, it doesn't work.

**Comment by balysv** [comment]
"When switching between different states, it works, but when it's on the same state, it doesn't work." 

Yes, this is how it is supposed to work now. I'll put this as an enhancement

**Comment by AndroidDeveloperLB** [comment]
Oh, thank you.

**Comment by balysv** [comment]
Also #20 might be fixed as well

**Comment by AndroidDeveloperLB** [comment]
Thanks.

**Comment by AndroidDeveloperLB** [comment]
wait, so the code got merged? is it on the repository?

**Comment by balysv** [comment]
A new release was publishes. Update your dependency version `1.5.1`

**Comment by AndroidDeveloperLB** [comment]
what do I need to do to make it work? 
What should I write in code, so that clicking on the burger will show a clicking effect, even if it doesn't switch to a different state?
