### ISSUE TITLE
why min sdk in 9? and support for "SlidingMenu"

### ISSUE THREAD

**Issue by amirghm** [balysv/material-menu#30]
Hi thank you for Amazing library

but why it need min sdk 9?
and did it support animation for "SlidingMenu" library?

thanks

**Comment by balysv** [comment]
It was little effort for the benefit of others to lower the min sdk, I don't see any downsides apart from the small NineOldDroids dependency
The animation is just a `Drawable` so you can use it with whatever library you like. Just use `MaterialMenuDrawable` directly.
