### ISSUE TITLE
MaterialMenuIconCompat seems to overrides actionbar background color

### ISSUE THREAD

**Issue by mortenholmgaard** [balysv/material-menu#32]
I have a navigationdrawer and actionbar working fine also with the MaterialMenu.

But when I try to change the background color of the ActionBar it works fine when I uncomment the MaterialMenu but when I use it, the background color is always black. I am using the windowActionBarOverlay to get the background behind the actionbar, which also could be the part not working properly with MaterialMenu. It seems like a bug.

    materialMenu = new MaterialMenuIconCompat(this, Color.WHITE, MaterialMenuDrawable.Stroke.THIN);
    // if I uncomment this line(and others using it) the background color is correct

Styling:

    <style name="AppTheme" parent="Theme.AppCompat">
        <item name="android:actionBarStyle">@style/ActionBar</item>
        <item name="actionBarStyle">@style/ActionBar</item>
        <item name="colorPrimaryDark">@color/statusbar</item>
    </style>

    <style name="ActionBar" parent="@style/Widget.AppCompat.ActionBar">
        <item name="android:background">#4C000000</item>
        <item name="android:windowActionBarOverlay">true</item>

        
        <item name="background">#4C000000</item>
        <item name="windowActionBarOverlay">true</item>
    </style>

**Comment by balysv** [comment]
I assume you are using `material-menu-toolbar` package and do not use `Toolbar`, so the only code that runs on the ActionBar when initializing `MaterialMenuIconCompat` is:

```java
        ActionBar actionBar = ((ActionBarActivity) activity).getSupportActionBar();
        actionBar.setDisplayShowHomeEnabled(true);
        actionBar.setDisplayUseLogoEnabled(false);
        actionBar.setHomeButtonEnabled(true);
        actionBar.setDisplayHomeAsUpEnabled(true);
        actionBar.setDefaultDisplayHomeAsUpEnabled(true);
        actionBar.setHomeAsUpIndicator(getDrawable());
```

which does not affect the background. Also, `MaterialMenu` is just a `Drawable` that replaces the navigation/home icon and has no control of the ActionBar that holds it.

Could you give more of code of `ActionBar` and `MaterialMenu` initialization?

**Comment by mortenholmgaard** [comment]
I  tried to remove all ActionBar configuration and I still had the problem. But I finally found the problem. I had windowActionBarOverlay style in the ActionBar style and not the general AppTheme style.
But how that worked without an icon and not with an icon I don't know.
