### ISSUE TITLE
Basic integration in Android Studio

### ISSUE THREAD

**Issue by kmuralidharan91** [balysv/material-menu#33]
@balysv @ming13 : When i follow the instructions given in read me (by compiling all 4) i facing 9 errors in my sample project.
Can you please make the readme (using the library) more easier and also a demonstration video if possible.
Do we need to include all these in my apps build.gradle
// stock actionBar
compile 'com.balysv.materialmenu:material-menu:1.x.x'

// Toolbar and ActionBarCompat-v21 (includes support-v7:21.0.x)
compile 'com.balysv.materialmenu:material-menu-toolbar:1.x.x'

// actionBarCompat-v20 (up to support-v7:20.0.0 - does not support Toolbar)
compile 'com.balysv.materialmenu:material-menu-abc:1.x.x'

// actionBarSherlock
compile 'com.balysv.materialmenu:material-menu-abs:1.x.x'

**Comment by SimenCodes** [comment]
Hi!
I'm not the developer of this, I'm just another user. You only need to import one of these, depending on which action bar type you use. Importing all of them is probably what triggers all those errors.

**Comment by balysv** [comment]
Yes, it's exactly as @SimenCodes mentioned. You only pick a single import line, depending on what ActionBar version or Toolbar you use
