### ISSUE TITLE
set Scale programmatically

### ISSUE THREAD

**Issue by lotdrops** [balysv/material-menu#35]
Hey!
My arrow drawable looks bigger than the stock one, and I thought the "scale" setting would allow me to change it (does it do this?), but I can't find the method to set it programmatically.
Is the method missing? 
And how do I change the size?

**Comment by balysv** [comment]
Scale is only used for debugging purposes and should be ignored in most of the cases. 
There is no actual way to adjust the icon size, it is hardcoded into the drawable.
