### ISSUE TITLE
Appear animation

### ISSUE THREAD

**Issue by slaviki** [balysv/material-menu#40]
Hello.

Is it possible to animate appearance of material icon. I want to animate a situation when there was no icon in toolbar and animate, for example, appearance of arrow button.

**Comment by balysv** [comment]
I would suggest getting the underlying `MaterialMenuDrawable` reference using `MaterialMenu.getDrawable()` and animating the `alpha` property using a `ObjectAnimator`.

**Comment by slaviki** [comment]
What about slide in animation, like in Gmail app when you select multiple letters?

**Comment by balysv** [comment]
That isn't currently possible on `MaterialMenuDrawable` api. 
You could animate the translation of the whole view that is holding the `Drawable` though.

**Comment by slaviki** [comment]
Yeah, but it will be great if you add this feature in future releases.

**Comment by balysv** [comment]
Will not be implemented since it can be achieved using View animation framework
