### ISSUE TITLE
Applying the CHECK animation to CAB

### ISSUE THREAD

**Issue by AkshayChordiya** [balysv/material-menu#43]
Hi,

I'm extremely happy with this library. And I was thinking to add the `Check` animation to the Contextual Action Bar, is it possible to do it or I need to write a Custom View for CAB.

**Comment by balysv** [comment]
Since `MaterialMenuDrawable` is a subclass of `Drawable`, you should be able to put it anywhere you want. There is also `MaterialMenuView` which is a custom view wrapper that might help you.

**Comment by AkshayChordiya** [comment]
Thanks for the reply. I'll try to do that.

On Thu, Jun 25, 2015, 12:07 AM Balys Valentukevicius <
notifications@github.com> wrote:

> Since MaterialMenuDrawable is a subclass of Drawable, you should be able
> to put it anywhere you want. There is also MaterialMenuView which is a
> custom view wrapper that might help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balysv/material-menu/issues/43#issuecomment-114975314>
> .
>
-- 

Regards,
Akshay Chordiya
