### ISSUE TITLE
Sloppy animation, if playing and in the same time keyboard is appearing on screen

### ISSUE THREAD

**Issue by southerton81** [balysv/material-menu#50]
I've been using your lbrary for animation the burger-to-arrow icon transition, in a SerchView (SearchView back arrow animates to burger when SearchView collapses, and vice versa). The issue I experienced is: when the soft keyboard show/hide occurs in the same time with the animation, then the animation becomes jerky, loosing a lot of frames. This situation happens on every phone I have. So I did a workaround, like this 

```
 private void animateToBurgerIcon() {
                if (mHandler == null) mHandler = new Handler();
                mHandler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        if (!MyFragment.this.isVisible()) {
                         toolbarMorphDrawable.animateIconState(MaterialMenuDrawable.IconState.BURGER);
                      searchMorphDrawable.animateIconState(MaterialMenuDrawable.IconState.BURGER);
                        } else {
                            mHandler.postDelayed(this, 20);
                        }
                    }
                }, 20);
            }
```

It checks whether the fragement I use is already visible (along with keyboard), and only then starts animation, which resolves the problem, but at the cost of strting animation a little later.

Maybe there could be some more ingenious solution for this problem?

**Comment by balysv** [comment]
No solution really. Software keyboards usually take a lot of resources and will jitter any animation run at the time they are opening.
