### ISSUE TITLE
SharedElements

### ISSUE THREAD

**Issue by MuhamedFathy** [balysv/material-menu#57]
Is there any way to share `MaterialMenuDrawable` between activities?

e.g. I have **hamburger** icon in the `FirstActivity` and want to animate it to **arrow** in the `SecondActivity`.

**Comment by balysv** [comment]
I'm afraid Android SDK does not allow sharing drawables between activities safely (without memory leaks). What you could potentially do is to run your icon animation on the second activity when it starts up (assuming a shared Toolbar). It might give the effect you want.
