### ISSUE TITLE
Adding to build.gradle issues

### ISSUE THREAD

**Issue by Technologx** [balysv/material-menu#58]
I'm running into this issue when I attempt to add this to my build.gradle.

Error:(31, 13) Failed to resolve: com.balysv.materialmenu:material-menu-abc:2.0.0
Error:(28, 13) Failed to resolve: com.balysv.materialmenu:material-menu-toolbar:2.0.0
Error:(34, 13) Failed to resolve: com.balysv.materialmenu:material-menu-abs:2.0.0

Here's my gradle code:

````
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.technologx.wallpaperzdash"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // stock actionBar
    compile 'com.balysv.materialmenu:material-menu:2.0.0'

// Toolbar and ActionBarCompat-v21 (includes support-v7:21.0.x)
    compile 'com.balysv.materialmenu:material-menu-toolbar:2.0.0'

// actionBarCompat-v20 (up to support-v7:20.0.0 - does not support Toolbar)
    compile 'com.balysv.materialmenu:material-menu-abc:2.0.0'

// actionBarSherlock
    compile 'com.balysv.materialmenu:material-menu-abs:2.0.0'
}
````

**Comment by balysv** [comment]
Those were dropped with the `2.0.0` release. You only need `compile 'com.balysv.materialmenu:material-menu:2.0.0` and implement the toolbar/abc/abs integration yourself.

If you still want to use the deprecated libraries, please refer to https://github.com/balysv/material-menu/blob/master/README-1.0.md

**Comment by Technologx** [comment]
Just I just need that 1 compile line?

**Comment by balysv** [comment]
Yes

**Comment by Technologx** [comment]
Alright cool thank you &amp; sorry I'm learning Android coding still new to it.

**Comment by balysv** [comment]
No problem at all :)

**Comment by Technologx** [comment]
So if I have different view for the drawer do I need to have the menu code in each of their activity java files? Sorry trying to learn &amp; make sure I'm doing things right.

**Comment by balysv** [comment]
It depends. It's ok to do that, but it's worth making some shared code that handles menu code and use it across all your activities.

**Comment by Technologx** [comment]
So do a import through all my activities I getcha thank you. I edited up creating a separate java called menu.
